name: Format code
on: [push]

jobs:
  babel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Babel
        run: npm install @babel/core @babel/cli @babel/plugin-transform-arrow-functions
      - name: Format code
        run: ./node_modules/.bin/babel lib --out-dir lib --plugins=@babel/plugin-transform-arrow-functions
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "format code"
          file_pattern: "lib/*.js" # Prevent auto-commit from commiting the node_modules used in the workflow
  prettier:
    needs: babel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Prettier
        run: npm install --global prettier
      - name: Format code
        run: npx prettier --write .
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "format code"
