name: Format code
on: [push]

jobs:
  babel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - name: Install Babel
        run: npm install @babel/core @babel/cli @babel/plugin-transform-arrow-functions
      - name: Format code
        run: ./node_modules/.bin/babel lib --out-dir lib --plugins=@babel/plugin-transform-arrow-functions
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "format code"
          file_pattern: "lib/*.js" # Prevent auto-commit from commiting the node_modules used in the workflow
  prettier:
    needs: babel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Prettier
        run: npm install --global prettier
      - name: Format code
        run: npx prettier --write .
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "format code"
  publish-build:
    needs: prettier
    if: contains(steps.changed-files.outputs.all_modified_files, 'package.json')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm test
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
