name: Format code using Prettier
on: 
  repository_dispatch:
    types: [babel-finish]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install Prettier
        run: npm install --global prettier
      - name: Format code
        run: npx prettier --write .
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "format code"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ErrorGamer2000/scratch3-api
          event-type: prettier-finish
          client-payload: '{"update": ${{github.event.client_payload.update}}}'
